; read settings ini
IniRead, Ip, settings.ini, Settings, ip
IniRead, AutoUpdateIni, settings.ini, Settings, auto_update
IniRead, LanguageIni, settings.ini, Settings, language
IniRead, DatabaseIni, settings.ini, Settings, db
IniRead, InstallMethodIni, settings.ini, Settings, install_method
IniRead, AutoInstallIni, settings.ini, Settings, auto_install
IniRead, ShowCiIni, settings.ini, Settings, show_ci

; read ciconfig ini
IniRead, DriveLetter, settings.ini, CiConfig, drive_letter
IniRead, MovablePath, settings.ini, CiConfig, movable_path
IniRead, Boot9Path, settings.ini, CiConfig, boot9_path
IniRead, SeedDbPath, settings.ini, CiConfig, seeddb_path

;read configured language from ini
IniRead, txtDbMissing, languages.ini, %LanguageIni%, txtDbMissing
IniRead, txtBtnDownload, languages.ini, %LanguageIni%, txtBtnDownload
IniRead, txtBtnSettings, languages.ini, %LanguageIni%, txtBtnSettings
IniRead, txtStatus, languages.ini, %LanguageIni%, txtStatus
IniRead, txtDb, languages.ini, %LanguageIni%, txtDb
IniRead, txtSpeed, languages.ini, %LanguageIni%, txtSpeed
IniRead, txtSettings, languages.ini, %LanguageIni%, txtSettings
IniRead, txtLanguage, languages.ini, %LanguageIni%, txtLanguage
IniRead, txtSave, languages.ini, %LanguageIni%, txtSave
IniRead, txtCfu, languages.ini, %LanguageIni%, txtCfu
IniRead, txtUpdate, languages.ini, %LanguageIni%, txtUpdate
IniRead, txtCfuMsg, languages.ini, %LanguageIni%, txtCfuMsg
IniRead, txtUpdateFound, languages.ini, %LanguageIni%, txtUpdateFound
IniRead, txtNoUpdateFound, languages.ini, %LanguageIni%, txtNoUpdateFound
IniRead, txtNoGame, languages.ini, %LanguageIni%, txtNoGame
IniRead, txtDownloading, languages.ini, %LanguageIni%, txtDownloading
IniRead, txtInstalling, languages.ini, %LanguageIni%, txtInstalling
IniRead, txtIpNotConfigured, languages.ini, %LanguageIni%, txtIpNotConfigured
IniRead, txtSelectGame, languages.ini, %LanguageIni%, txtSelectGame
IniRead, txtIdle, languages.ini, %LanguageIni%, txtIdle
IniRead, txtRestart, languages.ini, %LanguageIni%, txtRestart
IniRead, txtAskRestart, languages.ini, %LanguageIni%, txtAskRestart
IniRead, txtFileSelect, languages.ini, %LanguageIni%, txtFileSelect
IniRead, txtSelect, languages.ini, %LanguageIni%, txtSelect
IniRead, txtClickText, languages.ini, %LanguageIni%, txtClickText
IniRead, txtSearch, languages.ini, %LanguageIni%, txtSearch
IniRead, txtProgress, languages.ini, %LanguageIni%, txtProgress
IniRead, txtBtnShowLink, languages.ini, %LanguageIni%, txtBtnShowLink
IniRead, txtLink, languages.ini, %LanguageIni%, txtLink
IniRead, txtSelInstallMethod, languages.ini, %LanguageIni%, txtSelInstallMethod
IniRead, txtDownloadOn3DS, languages.ini, %LanguageIni%, txtDownloadOn3DS
IniRead, txtDownloadOnPC, languages.ini, %LanguageIni%, txtDownloadOnPC
IniRead, txtConfigCustomInstall, languages.ini, %LanguageIni%, txtConfigCustomInstall
IniRead, txtFileNotSpecified, languages.ini, %LanguageIni%, txtFileNotSpecified
IniRead, txtInstall, languages.ini, %LanguageIni%, txtInstall
IniRead, txtCiWarning, languages.ini, %LanguageIni%, txtCiWarning
IniRead, txtSuccessDownload, languages.ini, %LanguageIni%, txtSuccessDownload
IniRead, txtInvalidSettings, languages.ini, %LanguageIni%, txtInvalidSettings
IniRead, txtNoAdmin, languages.ini, %LanguageIni%, txtNoAdmin
IniRead, txtNoSpecifyMvblNoExist, languages.ini, %LanguageIni%, txtNoSpecifyMvblNoExist
IniRead, txtNoSpecifyB9NoExist, languages.ini, %LanguageIni%, txtNoSpecifyB9NoExist
IniRead, txtNoSpecifySdbNoExist, languages.ini, %LanguageIni%, txtNoSpecifySdbNoExist
IniRead, txtNotCia, languages.ini, %LanguageIni%, txtNotCia
IniRead, txtDriveLetterInvalidOrNotExist, languages.ini, %LanguageIni%, txtDriveLetterInvalidOrNotExist
IniRead, txtAutoInstall, languages.ini, %LanguageIni%, txtAutoInstall
IniRead, txtShowCiCliWindow, languages.ini, %LanguageIni%, txtShowCiCliWindow
IniRead, txtMovableInvalid, languages.ini, %LanguageIni%, txtMovableInvalid
IniRead, txtB9Invalid, languages.ini, %LanguageIni%, txtB9Invalid
IniRead, txtSdbInvalid, languages.ini, %LanguageIni%, txtSdbInvalid
IniRead, txtInvalidDriveLetterFormat, languages.ini, %LanguageIni%, txtInvalidDriveLetterFormat
IniRead, txtDriveLetter, languages.ini, %LanguageIni%, txtDriveLetter
IniRead, txtInvalidDb, languages.ini, %LanguageIni%, txtInvalidDb